language: python
python:
- '3.6'
- 3.7-dev
- nightly
cache: pip
install:
- sudo apt-get update -q
- sudo apt-get install python-dev libpython-dev
- pip install -r ./requirements.txt
script:
- py.test . -v --cov . --cov-report term-missing
env:
- PYTHONPATH=.
deploy:
  provider: pypi
  user: linuxdaemon
  password:
    secure: a/9DQ94bLoPFGIxOsqZNUX/+xY0+kyIGRFzKbXL6uHdpQR6IkcWTiIMdfrCeb23JXx7HX2jB1Ocd4PR3x4FFV5HbMHret6pwsu8uDVz+2lIBPpytZy8Vr/MyXjHbQM2c0cSxTiDwO08EYuk3u6sHgGT3CZZSQDU2e8NM7tw0BFYlfWMFKZ2Y5in745wZFEn2rIatvApl+iGmuf1ThrKj7nyYTOk9QgoVxsNDJvpFkm+9op8T/KxG7IH+ztwekczv9FJmoDs0Xf3GgoGWB3cxr+aHy0HgLtB2oDrZpxzkhWhlaRVlPxKlmbmOXT7C8zJJY/1tXPVOrikqX2FD+MpcFxX2TngcpyKi7hF3917NtmC2aTvt7+vncXA0WAFK7pI2rBwjtiz2w59226j9D/a6nHb13LLSuzgb2NKySWmZlR7aMBRQMJ6FSzwNydEWZCrr9CAzKpwKCzRINdbYQWJWH22AqTwz4ou39XW+x0/qNrdzYryQ+I4e6BKyfME1NjKaY9vWhW/tkffpQdPHEeXJs5sRhwAz3jaxblHePwIFYgCrUkHbBxRIGjkgp6OnB9nQSoYkUf8S32rwzH5vstsKVjqiYYCoMJFZF6eHFWYA1owubUv+Xv1+INTZY0IgGym8yOBldTmnWWdG+AVEaDzCTvSCQvhAikIxC+XYv9C3rJk=
  distributions: sdist bdist_wheel
  on:
    tags: true
    repo: snoonetIRC/async-irc
    python: '3.6'
matrix:
  allow_failures:
  - python: 3.7-dev
  - python: nightly
