name: Update .pre-commit-config.yaml

on:
  schedule:
    - cron: '0 3 * * 1' # Every Monday at 03:00 UTC
  workflow_dispatch:

env:
  HATCH_VERSION: "1.17.1"

jobs:
  update-pre-commit-config:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: '3.14'

      - name: Install Hatch
        uses: pypa/hatch@257e27e51a6a5616ed08a39a408a21c35c9931bc # install
        with:
          version: "${{ env.HATCH_VERSION }}"

      - name: Update .pre-commit-config.yaml
        run: hatch run pre-commit:pre-commit autoupdate --freeze

      - name: Run pre-commit
        run: hatch run pre-commit:run

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          commit-message: "chore(deps): Update .pre-commit-config.yaml"
          title: "chore(deps): Update .pre-commit-config.yaml"
          body: "Automated update of .pre-commit-config.yaml via scheduled workflow."
          branch: "update/pre-commit-config-yaml"
          base: ${{ github.ref_name }}
          labels: "update"
          reviewers: "linuxdaemon"
          assignees: "linuxdaemon"
          sign-commits: true
