name: Python tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  PYTHONUNBUFFERED: "1"
  FORCE_COLOR: "1"
  HATCH_VERSION: "1.16.5"

jobs:
  test:
    permissions:
      contents: read
      id-token: write

    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        python-version:
          - '3.10'
          - '3.11'
          - '3.12'
          - '3.13'
          - '3.14'
    name: "Test on ${{matrix.os}} with Python ${{matrix.python-version}}"
    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
      with:
        python-version: "${{matrix.python-version}}"
        cache: "pip"

    - name: Install Hatch
      uses: pypa/hatch@257e27e51a6a5616ed08a39a408a21c35c9931bc # install
      with:
        version: "${{ env.HATCH_VERSION }}"

    - run: hatch env find

    - name: Run type check
      run: hatch run types:check

    # - name: Run formatter
    #   run: hatch fmt --check

    - name: Run pre-commit
      run: hatch run pre-commit:run
      env:
        SKIP: nitpick,hatch-fmt,hatch-types

    - name: Run tests
      run: hatch test --python ${{ matrix.python-version }} --cover --randomize --retries 2 --retry-delay 1

    - uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
      with:
        name: "build-${{ matrix.python-version }}"
        fail_ci_if_error: true
        use_oidc: true

    - name: Upload test results to Codecov
      if: ${{ !cancelled() }}
      uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
      with:
        name: "build-${{ matrix.python-version }}"
        fail_ci_if_error: true
        use_oidc: true
        report_type: test_results
